version: '3.8'

services:
  nuxt:
    build:
      context: .
      dockerfile: containers/node/Dockerfile.dev  # ここでDockerfileのパスを指定
    container_name: nuxt3-container
    ports:
      - "3000:3000"
    depends_on:
      - postgres
      - minio
    volumes:
      - ./app:/app

  postgres:
    image: postgres:15
    container_name: postgres-container
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydatabase
      TZ: "Asia/Tokyo"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  minio:
    image: minio/minio:RELEASE.2025-02-28T09-55-16Z
    container_name: minio-container
    ports:
      - "9000:9000"  # S3 API
      - "9090:9090"  # Web UI
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9090"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

  createbuckets:
    build:
      context: ./containers/mc
      dockerfile: Dockerfile
    container_name: minio-setup
    depends_on:
      - minio

volumes:
  postgres_data:
  minio_data:
