# Node.js 公式イメージを使用
FROM node:22.9.0-alpine3.19

# 作業ディレクトリを設定
WORKDIR /app

# 依存関係をコピーしてインストール
COPY app/package.json app/package-lock.json ./
RUN npm install

# アプリケーションファイルをコピー
COPY app/ .
COPY app/prisma ./prisma/

RUN npx prisma generate

# 必要なパッケージのインストール
RUN apk update \
    && apk add --no-cache bash

# AWS App Runnerでデプロイした際、AWSがどのIPアドレスを割り当てても動作するように設定
ENV HOST 0.0.0.0
# ポート3000を開放
EXPOSE 3000

RUN npm run build

# Nuxtアプリを起動
CMD ["npm", "run", "start"]